### ISSUE TITLE
linux: consider not depending on libsystemd

### ISSUE THREAD

**Issue by lilmike** [samtupy/nvgt#106]
I would like to see if it's possible to drop the build dependancy on libsystemd, as this prevents several distros, such as alpine, void linux, from compiling nvgt successfully. Games built for linux do run fine with an app image for these platforms, but building the toolkit is impossible on these platforms.

**Comment by ethindp** [comment]
@lilmike To be clear, nvgt itself does not depend on libsystemd. The sd_notify plugin, however, does depend on it's existence. That plugin is an entirely optional component, however.

**Comment by samtupy** [comment]
The command to alter this behavior, with scons, would be something like `scons -s no_systemd_notify_plugin=1
I'd entirely be willing to add a note to the readme about this plugin, it seems like a good opportunity to demonstrate disabling plugins directly along with a practical situation where one may wish to do so.

**Comment by ethindp** [comment]
This plug-in can also be a no-op via [`__has_include`](https://en.cppreference.com/w/cpp/preprocessor/include), but scons would still need to handle the linking part.

**Comment by samtupy** [comment]
Oooo thanks @ethindp, I've not seen this directive before, yeah this just got way easy to fix because of that. I'll wrap sd_notify.cpp to use this __has_include directive, then will modify the SConscript for that plugin to only link with libsystemd.so if we can find it.
