### ISSUE TITLE
dynamic_menu errors out, 

### ISSUE THREAD

**Issue by patricus3** [samtupy/nvgt#18]
line: 94 (26)
ERROR: Identifier 'joystick' is not a data type in global namespace
I'm running out of a git build because it was easier for me to find the includes and see what stuff I can work with, plus, it's a fun challenge to see if I can build nvgt myself, and I can easily.

**Comment by TheQuinbox** [comment]
Hi,
it looks like dynamic_menu was never ported off of using bgt_compat. If uou \#include "bgt_compat.nvgt" at the top of your script or dynamic_menu, it should work. I've already fixed audio_form, speech and sound_pool using bgt_compat, dynamic_menu will happen, hopefully soon.
