### ISSUE TITLE
Pack file broken when used in soundpool

### ISSUE THREAD

**Issue by ogomez92** [samtupy/nvgt#4]
Hello,
I was trying to port an old game which used pack files, so I've been digging around the source code for the pack object (which btw is undocumented).

I ran the test/quick/pack.nvgt in your quick test in your repo and it worked, but once you try to use it into a soundpool you get the following error. Note that this error also threw a lot of seemingly unrelated things.

Thanks for checking.

file: D:/code/nvgt/repo/test/quick/packsound.nvgt
line: 7 (1)
INFO: Compiling void main()

file: D:/code/nvgt/repo/test/quick/packsound.nvgt
line: 30 (17)
ERROR: No appropriate opAssign method found in 'pack' for value assignment

file: C:/nvgt/include/sound_pool.nvgt
line: 112 (2)
INFO: Compiling void sound_pool_item::update_listener_position(float, float, float, float)

file: C:/nvgt/include/sound_pool.nvgt
line: 173 (24)
ERROR: No matching symbol 'cosine'

file: C:/nvgt/include/sound_pool.nvgt
line: 112 (2)
INFO: Compiling void sound_pool_item::update_listener_position(float, float, float, float)

file: C:/nvgt/include/sound_pool.nvgt
line: 174 (14)
ERROR: No matching symbol 'sine'

file: C:/nvgt/include/sound_pool.nvgt
line: 581 (2)
INFO: Compiling int sound_pool::get_sound_by_owner(string, int = 0)

file: C:/nvgt/include/sound_pool.nvgt
line: 583 (8)
ERROR: No matching symbol 'string_left'

file: C:/nvgt/include/sound_pool.nvgt
line: 605 (2)
INFO: Compiling bool sound_pool::update_sounds_3d(string, int, int, int, double = - 1)

file: C:/nvgt/include/sound_pool.nvgt
line: 607 (34)
ERROR: No matching symbol 'string_left'

file: C:/nvgt/include/sound_pool.nvgt
line: 628 (2)
INFO: Compiling bool sound_pool::set_sounds_rotation(string, double, vector)

file: C:/nvgt/include/sound_pool.nvgt
line: 630 (34)
ERROR: No matching symbol 'string_left'

file: C:/nvgt/include/sound_pool.nvgt
line: 639 (2)
INFO: Compiling bool sound_pool::set_sounds_amp(string, int, float)

file: C:/nvgt/include/sound_pool.nvgt
line: 641 (8)
ERROR: No matching symbol 'string_left'

file: C:/nvgt/include/sound_pool.nvgt
line: 648 (2)
INFO: Compiling bool sound_pool::destroy_sounds(string)

file: C:/nvgt/include/sound_pool.nvgt
line: 650 (8)
ERROR: No matching symbol 'string_left'

**Comment by ogomez92** [comment]
Here is the test that I used, note that I only added the soundpool at the end without modifying anything else:

void main() {
	pack_set_global_identifier("testpack");
	pack p;
	if (!p.open("packsound.dat", PACK_OPEN_MODE_CREATE)) {
		alert("Oh no!", "Couldn't create pack");
		return;
	}
	if (!p.add_file("C:\\windows\\media\\ding.wav", "ding")) {
		alert("An unfortunate error indeed", "Can't add file to pack");
		exit();
	}
	alert("test", p.size + " files now in pack!");
	p.close();
	if (!p.open("packsound.dat", PACK_OPEN_MODE_READ)) {
		alert("Oh no!", "Couldn't open pack");
		return;
	}
	sound s;
	s.load("ding", p);
	s.play_wait();
	s.close();
	
	sound_pool pool;
	pool.pack_file = p;
	p.close();
}

**Comment by TheQuinbox** [comment]
Try changing:
`pool.pack_file = p;`
to:
`@pool.pack_file = @p;`
Both sound.load() and sound_pool.pack_file expect a pack handle.
Apologies also, the pack class is indeed currently undocumented because there are plans to update it soon, and I didn't want to write a bunch of out-of-date docs.

**Comment by ogomez92** [comment]
Oh they expect a pack handle? In the test I saw:
s.load("ding", p);

also no worries, I know that this was a relatively internal project, I understand the lack of docs, was just pointing it out.

**Comment by ogomez92** [comment]
OK, the line you suggested works, thanks.

**Comment by samtupy** [comment]
As an aside, in response to your curiosity about the `sound.load(string filename, pack@);` and how we did not use an @ character when passing p to the handle, the reason that this works is because Angelscript is smart enough to implicitly cast the passed value to a handle. The reason you need to use an @ character when assigning to a sound pool though is because the compiler doesn't have enough information to figure out whether you'd like to call the opAssign method on an existing pack or whether you'd like to reassign the handle without that extra denotation, where as there is really only one option in the context of a function argument.

Hopefully that explains that seeming oddity, have fun!
