### ISSUE TITLE
can't install it on MacOS

### ISSUE THREAD

**Issue by Muamalaljanahi** [samtupy/nvgt#43]
hi
when i try to install it I get this error
"“nvgt.app” is damaged and can’t be opened. You should move it to the Trash."

**Comment by braillescreen** [comment]
Hi there.

This is due to NVGT's app bundle not being signed.

You can fix this by running the following in your terminal.
```
xattr -c /Applications/NVGT.app
```

Hope this helps!

**Comment by Muamalaljanahi** [comment]
@braillescreen thank you, I am getting another issue Now the nvgt crashes every time I open it

**Comment by samtupy** [comment]
Hi,
Have you read the troubleshooting section in this blog post?
https://nvgt.gg/blog/2024-06-03-48-hours-post-launch-updates.html
In this case, `brew install libgit2`

**Comment by Muamalaljanahi** [comment]
> Hi, Have you read the troubleshooting section in this blog post? https://nvgt.gg/blog/2024-06-03-48-hours-post-launch-updates.html In this case, `brew install libgit2`

thank you @samtupy it works now
