### ISSUE TITLE
I can't build using just the windev.zip on Windows

### ISSUE THREAD

**Issue by valiant8086** [samtupy/nvgt#56]
I tried to build, thinking if I can get to the point where I can see if I'm breaking things resulting in the code not running anymore I might be able to start contributing simple things to the actual code.

On the one hand, I'm not sure what testing is going to look like. Do I just move the final .exe into replace the one in c:\nvgt and then try to run an nvgt script, ideally one that would take advantage of what ever change I'm trying to create?

Here is what I got when I ran scons. It sounds to me like I'm missing Angelscript.obj? I don't have an angelscript.obj in scr, I have an .h and a .cpp. I just pulled and I just downloaded windev following the link in readme.md.

This is probably super obvious? But running on Windows 10, ltsc 2021 x64.

Microsoft Windows [Version 10.0.19044.4412]
(c) Microsoft Corporation. All rights reserved.

C:\code\myNvgt>scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fobuild\obj_src\UI.obj /c src\UI.cpp /TP /nologo /EHsc /J /MT /Z7 /std:c++20 /GF /Zc:inline /O2 /bigobj /permissive- /DPOCO_STATIC /DNDEBUG /DUNICODE /DNVGT_BUILDING /DNO_OBFUSCATE /Iwindev\include /IASAddon\include /Idep
'cl' is not recognized as an internal or external command,
operable program or batch file.
cl /Fobuild\obj_src\angelscript.obj /c src\angelscript.cpp /TP /nologo /EHsc /J /MT /Z7 /std:c++20 /GF /Zc:inline /O2 /bigobj /permissive- /DPOCO_STATIC /DNDEBUG /DUNICODE /DNVGT_BUILDING /DNO_OBFUSCATE /Iwindev\include /IASAddon\include /Idep
scons: *** [build\obj_src\UI.obj] Error 1
'cl' is not recognized as an internal or external command,
operable program or batch file.
scons: *** [build\obj_src\angelscript.obj] Error 1
scons: building terminated because of errors.

C:\code\myNvgt>

**Comment by samtupy** [comment]
Hi,
Sorry about that, the readme is making an assumption that it shouldn't and assumes the user has a dev environment on the system they want to install using. I'll add some clarifications to that document, thanks for the reminder!
You want to download [visual studio build tools](https://visualstudio.microsoft.com/downloads/) or visual studio 2022 with the desktop development with c++ workload.

**Comment by samtupy** [comment]
OK, I updated the readme to clarify this in commit 8089fe458331460ce744dcf9b6b69c5c8e0527f4

I accidentally forgot to close this issue from that commit's message, so doing that here. Please feel free to open another issue if you still have issues building after the development environment is established.
