### ISSUE TITLE
File system new dialog methods request

### ISSUE THREAD

**Issue by harrymkt** [samtupy/nvgt#61]
Hello.
I hope this request will be useful for all whom are working with the file system.

So, request is, to add 4 new functions, `open_files_dialog`, `save_file_dialog`, `open_folders_dialog`, and `save_folder_dialog`.

Also, all the open methods should have the ability for multiselect, and custom texts, and possibly custom wildcard patterns.

Save methods should have the ability to have custom texts, and possibly wildcard patterns.

<br>

These methods will be very useful, for instance, to show up the dialog to change game config folder location, etc.

Thanks.

**Comment by samtupy** [comment]
This has been planned for a while, we are waiting to either upgrade to SDL3 which has these functions or to use libtinyfiledialogs in the meantime. We'll get to it though, Thanks.

**Comment by harrymkt** [comment]
Seems we have those functions committed already, thanks!
