### ISSUE TITLE
Form. Inclood the f2 key to be changing the keyboard ekko by default like stw, And like ctrl+f and ctrl+g was inclooded by default

### ISSUE THREAD

**Issue by peter1384** [samtupy/nvgt#77]
Currently, If we just create a simple windo and creat a multi line editbox in it for ourselves, By default, The ctrl+g and ctrl+f are available to us so we can use go to and search functions
But, if we want to be able to swich and use keyboard ekkos, we have to manually code it in our script, For example, I want to use characters and words ekko for my textbox, But I don't know How do I implement this in my code to become like stw myself, So, like those above functions, make the f2 key in audio form text boxes do the ekko job exactly like the stw inputs, And if somebody doesn't want it like that, They can change it in the form of their games, But otherwise, it can be like this and we can use it

**Comment by peter1384** [comment]
@samtupy This is really important for me As I can't do this myself, Can you please tell me do you agree and will you implement this? When I was opening This issue and now that i'm wrighting this comment, I'm hoping that you've forgot to do this and move it out of stw's private code and let everyone use f2 key for their ekkos raather than they code it first manually, and you agree with this, And it's not that you had a reason to add it in stw's private form code and not the shared nvgt public's form code, i'm a bit stressed. Thanks a lot!

**Comment by harrymkt** [comment]
Hello @peter1384.
Yes, that will be an useful option too. I can implement it if you wish, in which case Sam will merge the pull request.

**Comment by peter1384** [comment]
@harrymkt hi, yes yes please, please assighn f2 to it, and make it exactly like stw, which swiches between non, characters, words, and characters and words.
Please do it, i'm waiting for your pull request and as soon as you open it, i'll download the form.nvgt from your  pull request and try it out, And use it until it gets merged. Thanks, a lot!

**Comment by harrymkt** [comment]
#79 Pull requested @peter1384

**Comment by peter1384** [comment]
@harrymkt Thanks so much! it is exactly as I wanted it, and I tested everything, it works as perfectly expected! I'm using this now until it gets merged, so Then I can use it in the main nvgt, Thanks again a lot!
